apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-controller
  namespace: dev-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: custom-controller
  template:
    metadata:
      labels:
        app: custom-controller
    spec:
      serviceAccountName: controller-sa
      containers:
      - name: controller
        image: docker.io/animeshsri98/controller-watcher:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000