apiVersion: v1
kind: Service
metadata:
  name: controller-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: custom-controller
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP